---
name: cygal-test-check

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Nodejs with npm caching
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'yarn'
    - uses: actions/cache@v3
      with:
          path: cygal/package-lock.json
          key: ${{ runner.os }}-${{ node-version }}-cygal-${{ hashFiles('**/cygal/package-lock.json') }}  # yamllint disable-line rule:line-length
    - name: Install playwright
      run: |
        yarn playwright install
    - name: Install local dependencies
      run: cd cygal && yarn install --frozen-lockfile
    - name: Run tests
      run: cd cygal && yarn test
    - name: Run checks
      run: cd cygal && yarn check
