---
name: cygal-test-check

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main, develop]

jobs:
  cygal-test-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs with npm caching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: cygal/yarn.lock
      - uses: actions/cache@v3
        with:
          path: cygal/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-cygal-${{ hashFiles('**/cygal/yarn.lock') }}  # yamllint disable-line rule:line-length
      - name: Install playwright
        run: |
          yarn playwright install
      - name: Install local dependencies
        run: cd cygal && yarn install --frozen-lockfile
      - name: Run tests
        run: cd cygal && yarn test
      - name: Run checks
        run: cd cygal && yarn check
