name: Lighthouse
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb dbus-x11 --no-install-recommends
          sudo apt-get install --assume-yes chromium-browser
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: cygal yarn install and build
        run: |
          cd cygal && yarn install && yarn build
      - name: Install lighthouse and run
        run: |
          which chromium-browser
          yarn global add lighthouse@9.6.1 @lhci/cli@0.8.2
          cd cygal && export LIGHTHOUSE_CHROMIUM_PATH=/snap/bin/chromium-browser; lhci autorun --collect.settings.chromeFlags=--no-sandbox
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
