name: Lighthouse
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get install wget
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: cygal yarn install and build
        run: |
          cd cygal && yarn install && yarn build
      - name: Install lighthouse and run
        run: |
          wget "https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots" --no-check-certificate -q -O chrome.zip && unzip chrome.zip
          export DISPLAY=:99.0
          export CHROME_PATH="$(pwd)/chrome-linux/chrome"
          sh -e /etc/init.d/xvfb start
          sleep 3
          yarn global add lighthouse@9.6.1 @lhci/cli@0.8.2 chromium-launcher
          cd cygal && lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
