name: playwright-test

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nodejs with npm caching
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: npm
        cache-dependency-path: cygal/package-lock.json
    - name: Install playwright
      run: |
        npx playwright install
    - name: Install local dependencies
      run: cd cygal && npm ci
    - name: Run npm test
      run: cd cygal && npm run test
