name: playwright-test

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nodejs with yarn caching
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: yarn
    - name: Install playwright
      run: |
        npx playwright install
    - name: Install local dependencies
      run: cd cygal && yarn
    - name: Run yarn test
      run: cd cygal && yarn test
