name: pre-commit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Setup Nodejs with npm caching
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: npm
        cache-dependency-path: cygal/package-lock.json
    - name: Install local dependencies
      run: cd cygal && npm ci
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
