---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: 18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Nodejs with npm caching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: cygal/yarn.lock
      - uses: actions/cache@v3
        with:
          path: cygal/yarn.lock
          key: ${{ runner.os }}-${{ matrix.node }}-cygal-${{ hashFiles('**/cygal/yarn.lock') }}  # yamllint disable-line rule:line-length
      - name: Install local dependencies
        run: cd cygal && yarn install --frozen-lockfile
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
