name: pre-commit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Setup Nodejs with npm caching
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache-dependency-path: cygal/package-lock.json
    - name: Install local dependencies
      run: cd cygal && yarn install --frozen-lockfile
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
